export enum ProjectStatus {
  BASIC_STUDIES='BASIC_STUDIES',
  DESIGN_IN_PROCESS='DESIGN_IN_PROCESS',
  UNDER_REVIEW='UNDER_REVIEW',
  CHANGE_REQUEST='CHANGE_REQUEST',
  CHANGE_PENDING='CHANGE_PENDING',
  REJECT='REJECT',
  APPROVED='APPROVED',
}
